### ISSUE TITLE
[BugBash] ExectionType name - remove hyperlinking

### ISSUE THREAD

**Issue by avdaredevil** [kubeflow/frontend#11]
## About
This issue is regarding the `ExecutionName` formatting looking like a link, but not doing anything, we will snub out this behavior for this release, and consider making it selectable in the next iteration sometime in Q2-3

## Solution
- Remove underline
- Remove hover styles

### Meta
/area metadata
/area front-end
/priority p1
/assign @avdaredevil
/cc @kwasi

**Comment by kwasi** [comment]
/remove-priority p1
/priority p0 

Updating priority to match bug bash prioritization.

**Comment by kwasi** [comment]
This is actually now obsolete with https://github.com/kubeflow/frontend/pull/22. Execution links now go to ExecutionDetails
