### ISSUE TITLE
[BugBash] Make execution cards very different from Artifact cards

### ISSUE THREAD

**Issue by avdaredevil** [kubeflow/frontend#14]
## About
This issue tackles the issue of execution cards being very similar to artifact cards in the UI.

## Solution
- [x] Update execution cards based on Mocks provided by @ajayalfred 
- [ ] _**Stretch:** Make edges and dots color corrected based on the status of relationship_

### Meta
/area metadata
/area front-end
/priority p1
/assign @avdaredevil
/cc @kwasi

**Comment by ajayalfred** [comment]
https://gallery.googleplex.com/projects/MCHbtQVoQ2HCZYbjDGnaKqEC/files/MCFtVo4CQinf5JM_HBb9FL1s

**Comment by ajayalfred** [comment]
![image](https://user-images.githubusercontent.com/2425179/73316135-f06a4000-41e6-11ea-8772-b1aa2f42038a.png)
