### ISSUE TITLE
[MLMD Lineage] Make execution card look different from Artifacts card

### ISSUE THREAD

**Issue by avdaredevil** [kubeflow/frontend#2]
## About
Feedback given by @neuromage after early demo. Cards look too similar and are hard to distinguish on certain screens.

@ajayalfred any thoughts on this?

### Meta
/area metadata
/area front-end
/priority p1
/assign @ajayalfred
/cc @kwasi @avdaredevil

**Comment by kwasi** [comment]
/remove-priority p1
/priority p0

Updating priority to match bug bash priority.

**Comment by avdaredevil** [comment]
Closing as it is a duplicate of #14
