### ISSUE TITLE
Move package under @kubeflow scope

### ISSUE THREAD

**Issue by kwasi** [kubeflow/frontend#24]
/priority p2

## Background

This came up in code review for the pipelines integration:

https://github.com/kubeflow/pipelines/pull/2918#discussion_r372185504

The ask is to move the package under `@kubeflow` scope so that imports are cleaner. 

It also has the added benefit of this package not being confused with https://www.npmjs.com/package/frontend

**Comment by Bobgy** [comment]
already resolved by https://github.com/kubeflow/pipelines/pull/2918
/close
