### ISSUE TITLE
[MLMD] No name is displayed in the Lineage Explorer for the TFX Taxi example

### ISSUE THREAD

**Issue by kwasi** [kubeflow/frontend#38]
/priority p0
/assign @kwasi 
/area front-end

## Bug

https://screenshot.googleplex.com/VdqOaPagkkM.png

## Repro Steps

* Installed KFP test version from marketplace
* Run TFX Taxi sample

**Comment by avdaredevil** [comment]
A note to add to this, while you work on it:
- The logic is much more simpler now, with a function called: [**_`getResourcePropertyViaFallBack()`_**](https://github.com/kubeflow/frontend/blob/master/src/mlmd/Utils.tsx#L39-L51)
  - Examples: **_[`getExecutionName()`](https://github.com/kubeflow/frontend/blob/master/src/mlmd/Utils.tsx#L59-L67), [`getResourceDescription()`](https://github.com/kubeflow/frontend/blob/master/src/mlmd/Utils.tsx#L82-L97)_**
